# Generated by Django 4.1.1 on 2022-09-17 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructure', '0002_trial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_file', models.FileField(upload_to='documents')),
            ],
        ),
    ]
