# Generated by Django 4.1.1 on 2022-09-17 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructure', '0003_frd'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Frd',
        ),
        migrations.DeleteModel(
            name='Trial',
        ),
    ]
