# Generated by Django 4.1.1 on 2022-12-17 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kolichestvo_postupaushih',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('god', models.IntegerField(null=True)),
                ('kolichestvo', models.IntegerField(null=True)),
            ],
        ),
    ]
