# Generated by Django 4.1.1 on 2022-12-19 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistika', '0002_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trudoustroystvo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('god', models.IntegerField(null=True)),
                ('trudoustroen', models.IntegerField(null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Kolichestvo_postupaushih',
            new_name='Kolichestvo_postupivshih',
        ),
    ]
