# Generated by Django 4.1.1 on 2022-12-19 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistika', '0003_trudoustroystvo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reyting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vuz', models.CharField(max_length=37, null=True)),
                ('kolichestvo', models.IntegerField(null=True)),
            ],
        ),
    ]
