# Generated by Django 4.1.1 on 2022-12-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=132, null=True)),
                ('description', models.CharField(max_length=700, null=True)),
                ('fees', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Technicum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=132, null=True)),
                ('description', models.CharField(max_length=700, null=True)),
                ('fees', models.IntegerField(null=True)),
            ],
        ),
    ]
