# Generated by Django 4.1.1 on 2022-09-18 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager', models.CharField(max_length=70)),
                ('characteristics', models.CharField(max_length=170)),
                ('whatsapp', models.CharField(max_length=70)),
                ('facebook', models.CharField(max_length=70)),
                ('instagramm', models.CharField(max_length=70)),
                ('telephone', models.CharField(max_length=70)),
                ('fax', models.CharField(max_length=70)),
                ('mail', models.CharField(max_length=700)),
                ('site', models.CharField(max_length=70)),
                ('adress', models.CharField(max_length=70)),
            ],
        ),
    ]
