# Generated by Django 4.1.1 on 2022-09-18 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admission',
            old_name='adress',
            new_name='address',
        ),
    ]
