# Generated by Django 4.1.1 on 2022-09-24 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OVuze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obzor', models.CharField(max_length=7000)),
                ('mission', models.CharField(max_length=7000)),
                ('history', models.CharField(max_length=7000)),
                ('strategy', models.CharField(max_length=7000)),
            ],
        ),
    ]
