# Generated by Django 4.1.1 on 2022-09-24 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovuze', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ovuze',
            name='fotka',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
