# Generated by Django 4.1.1 on 2022-09-24 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ovuze', '0004_alter_ovuze_fotka'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ovuze',
            name='fotka',
        ),
    ]
