# Generated by Django 4.1.1 on 2022-12-07 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovuze', '0005_remove_ovuze_fotka'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libriary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Prof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=70)),
                ('name', models.CharField(max_length=130)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=70)),
                ('fax', models.CharField(max_length=70)),
                ('address', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Stajirovka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=70)),
                ('description', models.CharField(max_length=130)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=70)),
                ('address', models.CharField(max_length=70)),
            ],
        ),
        migrations.DeleteModel(
            name='OVuze',
        ),
    ]
