# Generated by Django 4.1.1 on 2022-12-07 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovuze', '0006_libriary_prof_stajirovka_delete_ovuze'),
    ]

    operations = [
        migrations.AddField(
            model_name='stajirovka',
            name='foto',
            field=models.ImageField(null=True, upload_to='pr1/media/'),
        ),
    ]
