# Generated by Django 4.1.1 on 2022-12-07 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovuze', '0007_stajirovka_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stajirovka',
            name='foto',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
