# Generated by Django 4.1.1 on 2022-12-07 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovuze', '0008_alter_stajirovka_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Npa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('document', models.FileField(null=True, upload_to='materials')),
            ],
        ),
    ]
