# Generated by Django 4.1.1 on 2022-12-07 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovuze', '0009_npa'),
    ]

    operations = [
        migrations.AddField(
            model_name='npa',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='npa',
            name='description',
            field=models.CharField(max_length=300),
        ),
    ]
