# Generated by Django 4.1.1 on 2022-12-07 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovuze', '0010_npa_name_alter_npa_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='npa',
            name='document',
            field=models.FileField(null=True, upload_to='npa_materials'),
        ),
        migrations.AlterField(
            model_name='stajirovka',
            name='foto',
            field=models.ImageField(null=True, upload_to='stajirovka_fotos'),
        ),
    ]
