# Generated by Django 4.1.1 on 2022-12-08 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovuze', '0011_alter_npa_document_alter_stajirovka_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('foto', models.ImageField(null=True, upload_to='foto_gallery')),
            ],
        ),
    ]
