# Generated by Django 4.1.1 on 2022-12-28 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dekanat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dekan', models.CharField(max_length=33, null=True)),
                ('phone', models.CharField(max_length=37, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kafedra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45, null=True)),
                ('zav_kafedra', models.CharField(max_length=33, null=True)),
                ('phone', models.CharField(max_length=37, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('title', models.CharField(max_length=100, null=True)),
                ('dekan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='faculties.dekanat')),
                ('description', models.FileField(null=True, upload_to='faculty_materials')),
                ('Kafedras', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculties.kafedra')),
            ],
        ),
    ]
