# Generated by Django 4.1.1 on 2022-12-28 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculties', '0002_remove_faculty_kafedras_kafedra_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kafedra',
            name='address',
        ),
        migrations.AddField(
            model_name='faculty',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
