# Generated by Django 4.1.1 on 2022-12-28 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculties', '0003_remove_kafedra_address_faculty_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kafedra',
            name='faculty',
        ),
        migrations.AddField(
            model_name='faculty',
            name='kafedras',
            field=models.ManyToManyField(null=True, to='faculties.kafedra'),
        ),
    ]
