# Generated by Django 4.1.1 on 2022-12-28 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculties', '0006_dekanat_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='address',
        ),
    ]
