# Generated by Django 4.1.1 on 2023-01-03 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculties', '0008_remove_faculty_kafedras_kafedra_faculty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='description',
        ),
    ]
