# Generated by Django 4.1.1 on 2023-01-03 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculties', '0009_remove_faculty_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='kafedra',
            name='address',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
