# Generated by Django 4.1.1 on 2023-01-03 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculties', '0010_kafedra_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kafedra',
            name='phone',
            field=models.CharField(max_length=137, null=True),
        ),
        migrations.AlterField(
            model_name='kafedra',
            name='title',
            field=models.CharField(max_length=145, null=True),
        ),
        migrations.AlterField(
            model_name='kafedra',
            name='zav_kafedra',
            field=models.CharField(max_length=133, null=True),
        ),
    ]
