# Generated by Django 4.1.1 on 2022-12-06 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('aim', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('Профессора', 'Профессора'), ('Доктора', 'Доктора'), ('Доценты', 'Доценты'), ('Кандидаты', 'Кандидаты'), ('Старшие преподаватели', 'Старшие преподаватели'), ('Преподаватели', 'Преподаватели'), ('Лаборанты', 'Лаборанты')], default='Профессора', max_length=32)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
            ],
        ),
    ]
