# Generated by Django 4.1.1 on 2022-12-06 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glavnoe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('events', models.CharField(max_length=300)),
            ],
        ),
    ]
