# Generated by Django 4.1.1 on 2022-12-17 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazvanie_korpusa', models.CharField(max_length=30)),
                ('foto', models.ImageField(upload_to='structure')),
                ('address', models.CharField(max_length=45)),
            ],
        ),
    ]
